config_version = 13

[backdrop]
enabled        = true
blur_intensity = 0.5    # 0.0 (no blur) to 1.0 (max blur)
tint_intensity = 0.4    # 0.0 (no tint) to 1.0 (opaque tint)

[accessibility]
ui_scale = 1.0000000074505806

[bar.default]
center = [ "clock", "audio_visualizer" ]

[osd.kinds]
media = false

[control_center.calendar]
show_events_card = false

[location]
address = "tamil nadu trichy"

[weather]
refresh_minutes = 20

[shell]
polkit_agent = true
telemetry_enabled = true
app_icon_color = "on_surface"

[shell.launcher]
categories = false

[shell.panel]
launcher_placement = "floating"

[theme]
builtin = "Noctalia"
community_palette = "Oxocarbon"
custom_palette = "wonderful-surya-scaled-vib"
mode = "dark"
source = "wallpaper"
wallpaper_scheme = "m3-content"

[theme.templates]
builtin_ids = [ "alacritty", "emacs", "niri" ]

[widget.battery]
enabled = false

[widget.bluetooth]
enabled = false

[widget.brightness]
enabled = false

[widget.clock]
format = "{:%I:%M %p}"
timezone = "Asia/Kolkata"
tooltip_format = "{:%A, %d %B %Y - %H:%M}"

[widget.control-center]
enabled = false

[widget.launcher]
enabled = false

[widget.media]
enabled = false

[widget.network]
enabled = false

[widget.volume]
enabled = false

[widget.wallpaper]
enabled = false
