[env]
TERM = "xterm-256color"

[font]
size = 15.0

[font.normal]
# family = "FiraCodeNerdFont"
family = "JetBrainsMono Nerd Font"
style = "Regular"


[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 1.0

# ctrl + backspace to del word
[[keyboard.bindings]]
key = "Back"
mods = "Control"
chars = "\u0017"

[general]
live_config_reload = true
import = [
  "~/.cache/wal/colors-alacritty.toml"
]

