[general]
import = ["~/.config/alacritty/themes/noctalia.toml"]

[env]
TERM = "xterm-256color"
COLORTERM = "truecolor"

[window]
opacity = 0.95

[font]
size = 20.0

[font.normal]
family = "Noto Sans Mono"
