live_config_reload = true

[env]
TERM = "xterm-256color"

[font]
size = 10.0

[font.normal]
# family = "FiraCodeNerdFont"
family = "JetBrainsMono Nerd Font"
style = "Regular"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.63
# opacity = 1




[[keyboard.bindings]]
key = "Back"
mods = "Control"
chars = "\u0017"

[colors]

[colors.primary]
# background = "#000000"
background = "#16161e"
foreground = "#cdd6f4"
dim_foreground = "#7f849c"
bright_foreground = "#cdd6f4"

[colors.cursor]
text = "#1e1e2e"
cursor = "#f5e0dc"

[colors.vi_mode_cursor]
text = "#1e1e2e"
cursor = "#b4befe"

[colors.search.matches]
foreground = "#1e1e2e"
background = "#000000"

[colors.search.focused_match]
foreground = "#1e1e2e"
background = "#000000"

[colors.footer_bar]
foreground = "#1e1e2e"
background = "#000000"

[colors.hints.start]
foreground = "#1e1e2e"
background = "#000000"

[colors.hints.end]
foreground = "#1e1e2e"
background = "#000000"

[colors.selection]
text = "#1e1e2e"
# background = "#7C8BDA"
background = "#7f849c"

[colors.normal]
black = "#45475a"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#bac2de"

[colors.bright]
black = "#585b70"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#a6adc8"

[colors.dim]
black = "#45475a"
red = "#f38ba8"
green = "#a6e3a1"
yellow = "#f9e2af"
blue = "#89b4fa"
magenta = "#f5c2e7"
cyan = "#94e2d5"
white = "#bac2de"

[[colors.indexed_colors]]
index = 16
color = "#fab387"

[[colors.indexed_colors]]
index = 17
color = "#f5e0dc"
