import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

live_config_reload = true

[env]
TERM = "xterm-256color"

[font]
size = 10.0

[font.normal]
# family = "FiraCodeNerdFont"
family = "JetBrainsMono Nerd Font"
style = "Regular"


[window]
decorations = "buttonless"
dynamic_padding = false
# opacity = 0.63
# opacity = 0.80
opacity = 1



# ctrl + backspace to del word
[[keyboard.bindings]]
key = "Back"
mods = "Control"
chars = "\u0017"

