# my fav theme
# theme = "base16_transparent"
# theme = "base16_default"
# theme = "base16_terminal"
# theme = "dark_plus"
# theme = "gruvbox"
# theme = "curzon"
# theme = "dark_high_contrast"
# theme = "emacs"
# theme = "everforest_dark"
# theme = "material_oceanic"
# theme = "modus_vivendi"
# theme = "pop-dark"
# theme = "zenburn"
theme = "ayu_dark"
[editor]
line-number = "relative"
bufferline = "multiple"
cursorline = true
auto-save = true

# [editor.lsp]
# display-inlay-hints = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[editor.file-picker]
hidden = false

# To make search fully case sensitive 
# [editor.search]
# smart-case = false

[keys.normal]
C-g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]
esc = ["collapse_selection", "keep_primary_selection"]
"A-j" = [ "extend_to_line_bounds", "delete_selection", "paste_after" ]
"A-k" = [ "extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before" ]
# y = "yank_to_clipboard"

[keys.select]
"A-k" = ["yank_main_selection_to_clipboard", "delete_selection", "move_line_up", "paste_clipboard_before", "select_mode"]
"A-j" = ["yank_main_selection_to_clipboard", "delete_selection", "move_line_down", "paste_clipboard_before", "select_mode"]

[keys.insert]


[editor.statusline]
left = ["mode", "spinner", "file-name"]
# center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "N"
mode.insert = "I"
mode.select = "S"

# [language-server.harper-ls]
# command = "harper-ls"
# args = ["--stdio"]
