# theme = "base16_transparent"
theme = "base16_transparent"
# theme = "dark_plus"
# theme = "gruvbox"


[editor]
line-number = "relative"
# bufferline = "multiple"
cursorline = true
auto-save = true

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"

[keys.normal]
C-g = [":new", ":insert-output lazygit", ":buffer-close!", ":redraw"]
esc = ["collapse_selection", "keep_primary_selection"]
"A-k" = [ "extend_to_line_bounds", "delete_selection", "move_line_up", "paste_before" ]
"A-j" = [ "extend_to_line_bounds", "delete_selection", "paste_after" ]

[keys.select]
"A-k" = ["yank_main_selection_to_clipboard", "delete_selection", "move_line_up", "paste_clipboard_before", "select_mode"]
"A-j" = ["yank_main_selection_to_clipboard", "delete_selection", "move_line_down", "paste_clipboard_before", "select_mode"]

[keys.insert]


[editor.statusline]
left = ["mode", "spinner"]
center = ["file-name"]
right = ["diagnostics", "selections", "position", "file-encoding", "file-line-ending", "file-type"]
separator = "│"
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

# [language-server.harper-ls]
# command = "harper-ls"
# args = ["--stdio"]

# my name is "kishore"
# Key bindings for normal mode to trigger the custom command
