import = [
  "~/.config/alacritty/catppuccin-mocha.toml"
]

live_config_reload = true

[env]
TERM = "xterm-256color"

[font]
size = 15.0

[font.normal]
family = "FiraCodeNerdFont"
style = "Regular"

[window]
decorations = "buttonless"
dynamic_padding = false
opacity = 0.85


