-- Keymaps are automatically loaded on the VeryLazy event
-- Default keymaps that are always set: https://github.com/LazyVim/LazyVim/blob/main/lua/lazyvim/config/keymaps.lua
-- Add any additional keymaps here
-- vim.api.nvim_set_keymap("n", "e", ":Explore<CR>", { noremap = true, silent = true })
-- Define a function to create key mappings
-- vim.api.nvim_set_keymap("n", "dd", '"_dd', { noremap = true, silent = true })
