[colors.primary]
background = '#19120d'
foreground = '#eee0d7'

[colors.cursor]
text = '#19120d'
cursor = '#eee0d7'

[colors.vi_mode_cursor]
text = '#19120d'
cursor = '#ffb779'

[colors.search.matches]
foreground = '#534438'
background = '#c4ce68'

[colors.search.focused_match]
foreground = '#534438'
background = '#ffb779'

[colors.footer_bar]
foreground = '#534438'
background = '#eee0d7'

[colors.hints.start]
foreground = '#534438'
background = '#ecbe98'

[colors.hints.end]
foreground = '#534438'
background = '#ecbe98'

[colors.selection]
text = '#d8c3b3'
background = '#534438'


[colors.normal]
black   = '#534438'
red     = '#ffb4ab'
green   = '#ffb779'
yellow  = '#ecbe98'
blue    = '#c4ce68'
magenta = '#ffb779'
cyan    = '#ecbe98'
white   = '#eee0d7'


[colors.bright]
black   = '#a08d7f'
red     = '#ffb4ab'
green   = '#ffb779'
yellow  = '#ecbe98'
blue    = '#c4ce68'
magenta = '#ffb779'
cyan    = '#ecbe98'
white   = '#eee0d7'


[colors.dim]
black   = '#534438'
red     = '#ffb4ab'
green   = '#ffb779'
yellow  = '#ecbe98'
blue    = '#c4ce68'
magenta = '#ffb779'
cyan    = '#ecbe98'
white   = '#eee0d7'
