[colors.primary]
background = '#17130b'
foreground = '#ebe1d4'

[colors.cursor]
text = '#17130b'
cursor = '#ebe1d4'

[colors.vi_mode_cursor]
text = '#17130b'
cursor = '#f4bf45'

[colors.search.matches]
foreground = '#4f4635'
background = '#b6d166'

[colors.search.focused_match]
foreground = '#4f4635'
background = '#f4bf45'

[colors.footer_bar]
foreground = '#4f4635'
background = '#ebe1d4'

[colors.hints.start]
foreground = '#4f4635'
background = '#e0c38b'

[colors.hints.end]
foreground = '#4f4635'
background = '#e0c38b'

[colors.selection]
text = '#d2c5af'
background = '#4f4635'


[colors.normal]
black   = '#4f4635'
red     = '#ffb4ab'
green   = '#f4bf45'
yellow  = '#e0c38b'
blue    = '#b6d166'
magenta = '#f4bf45'
cyan    = '#e0c38b'
white   = '#ebe1d4'


[colors.bright]
black   = '#9b8f7b'
red     = '#ffb4ab'
green   = '#f4bf45'
yellow  = '#e0c38b'
blue    = '#b6d166'
magenta = '#f4bf45'
cyan    = '#e0c38b'
white   = '#ebe1d4'


[colors.dim]
black   = '#4f4635'
red     = '#ffb4ab'
green   = '#f4bf45'
yellow  = '#e0c38b'
blue    = '#b6d166'
magenta = '#f4bf45'
cyan    = '#e0c38b'
white   = '#ebe1d4'
