hl.on("hyprland.start", function()
  hl.exec_cmd("noctalia")
  hl.exec_cmd("flameshot")
  hl.exec_cmd("emacs --daemon")
  hl.exec_cmd("dbus-update-activation-environment --systemd WAYLAND_DISPLAY XDG_CURRENT_DESKTOP")
  hl.exec_cmd("systemctl --user start xdg-desktop-portal.service xdg-desktop-portal-hyprland.service")
  hl.exec_cmd("systemctl --user start opentabletdriver")
end)

hl.env("QT_QPA_PLATFORMTHEME", "qt6ct")
hl.env("XDG_CURRENT_DESKTOP", "Hyprland")
hl.env("XDG_SESSION_TYPE", "wayland")
hl.env("XCURSOR_SIZE", "24")
hl.env("HYPRCURSOR_SIZE", "24")
