require("monitors")
require("variables")
require("autostart")
require("appearance")
require("layouts")
require("misc")
require("input")
require("workspaces")
require("keybinds")
require("rules")

require("zoom")
require("shader")
require("noctalia").apply_theme()
