color0 #444937
color1 #ffb4ab
color2 #c5f35a
color3 #bacf89
color4 #75fd9c
color5 #aad540
color6 #bacf89
color7 #e2e4d3
color8 #8e937d
color9 #ffb4ab
color10 #c5f35a
color11 #bacf89
color12 #75fd9c
color13 #aad540
color14 #bacf89
color15 #e2e4d3

cursor                #e2e4d3
cursor_text_color     #12140b
background            #12140b
foreground            #e2e4d3
selection_foreground  #c4c9b1
selection_background  #444937
active_border_color   #c5f35a
inactive_border_color #444937
url_color             #c5f35a

active_tab_foreground   #263500
active_tab_background   #c5f35a
inactive_tab_foreground #c4c9b1
inactive_tab_background #444937
cursor_trail_color      #c4c9b1
