# Environment variables
term xterm-256color
env COLORTERM=truecolor

# Window
background_opacity 0.95

# Font settings
font_family      Noto Sans Mono
font_size        20.0
include themes/noctalia.conf
